# Generated by Django 3.0.5 on 2022-11-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
