# Generated by Django 3.0.5 on 2022-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0005_monument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.TextField(default='abc'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(default='abc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.TextField(default='abc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='abc'),
        ),
    ]
