# Generated by Django 3.0.5 on 2022-11-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0006_auto_20221112_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='Monument_city',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='Monument_image',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='Monument_location',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='Monument_name',
        ),
        migrations.AddField(
            model_name='monument',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='desc',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='inst',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='location',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='name',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='price_for',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='price_ind',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='reach',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='monument',
            name='time',
            field=models.TextField(default='abc'),
        ),
    ]
