# Generated by Django 3.0.5 on 2022-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0007_auto_20221113_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('monument_name', models.TextField(default='abc')),
                ('location', models.TextField(default='abc')),
                ('count_ind', models.TextField(default='abc')),
                ('count_for', models.TextField(default='abc')),
                ('count_free', models.TextField(default='abc')),
                ('price', models.TextField(default='abc')),
            ],
        ),
    ]
