# Generated by Django 3.0.5 on 2022-11-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0008_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='username',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
