# Generated by Django 3.0.5 on 2022-11-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Tape', '0009_tickets_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr-codes'),
        ),
    ]
